# ========================================
# Notification Service 설정
# ========================================

# ========================================
# 메시징 설정 (RabbitMQ Exchange)
# ========================================
messaging:
  exchange:
    reservation: tickatch.reservation
    ticket: tickatch.ticket
    notification-sender: tickatch.notification-sender
  email:
    exchange: tickatch.email
  sms:
    exchange: tickatch.sms
  mms:
    exchange: tickatch.mms
  slack:
    exchange: tickatch.slack